# this one is important
SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CMAKE_CXX_FLAGS           "-m64 ${CMAKE_CXX_FLAGS}" CACHE STRING "")
set(CMAKE_C_FLAGS             "-m64 ${CMAKE_C_FLAGS}" CACHE STRING "")
set(CMAKE_EXE_LINKER_FLAGS    "-m64 ${CMAKE_EXE_LINKER_FLAGS}" CACHE STRING "")
set(CMAKE_SHARED_LINKER_FLAGS "-m64 ${CMAKE_SHARED_LINKER_FLAGS}" CACHE STRING "")

set(ARCH 64 CACHE STRING "" FORCE)
set(BUILD_TARGET lin64 CACHE STRING "" FORCE)
